//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeachApplication.BusinessLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeachApplication.BusinessLayer.Resources.ClientValues", typeof(ClientValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api-version=3.0.
        /// </summary>
        internal static string ApiVersion {
            get {
                return ResourceManager.GetString("ApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string AuthorizationHeader {
            get {
                return ResourceManager.GetString("AuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1.
        /// </summary>
        internal static string BaseSpeechToTextRequestUri {
            get {
                return ResourceManager.GetString("BaseSpeechToTextRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.tts.speech.microsoft.com/cognitiveservices/v1.
        /// </summary>
        internal static string BaseTextToSpeechRequestUri {
            get {
                return ResourceManager.GetString("BaseTextToSpeechRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.cognitive.microsofttranslator.com/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.cognitive.microsoft.com/sts/v1.0/issueToken.
        /// </summary>
        internal static string GlobalAuthorizationUrl {
            get {
                return ResourceManager.GetString("GlobalAuthorizationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string JsonMediaType {
            get {
                return ResourceManager.GetString("JsonMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocp-Apim-Subscription-Key.
        /// </summary>
        internal static string OcpApimSubscriptionKeyHeader {
            get {
                return ResourceManager.GetString("OcpApimSubscriptionKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocp-Apim-Subscription-Region.
        /// </summary>
        internal static string OcpApimSubscriptionRegionHeader {
            get {
                return ResourceManager.GetString("OcpApimSubscriptionRegionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.api.cognitive.microsoft.com/sts/v1.0/issueToken.
        /// </summary>
        internal static string RegionAuthorizationUrl {
            get {
                return ResourceManager.GetString("RegionAuthorizationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/wav.
        /// </summary>
        internal static string WavAudioMediaType {
            get {
                return ResourceManager.GetString("WavAudioMediaType", resourceCulture);
            }
        }
    }
}
